<<<<<<< Updated upstream
iso6393dic ={'hbs':{'label':'Serbo-Croatian', 'for_espeak':'bs'}, #hr, #sr
'deu':{'label':'German', 'for_espeak':'de'},
'swe':{'label':'Swedish', 'for_espeak':'sv'},
'nor':{'label':'Norwegian', 'for_espeak':'no'},
'fin':{'label':'Finnish', 'for_espeak':'fi'},
'dan':{'label':'Danish', 'for_espeak':'da'},
'tir':{'label':'Tigrinya', 'for_espeak':''},
'spa':{'label':'Spanish', 'for_espeak':'es'},
'ita':{'label':'Italian', 'for_espeak':'it'},
'fra':{'label':'French', 'for_espeak':'fr'},
'ell':{'label':'Greek', 'for_espeak':'el'},
'hun':{'label':'Hungarian', 'for_espeak':'hu'},
'por':{'label':'Portuguese', 'for_espeak':'pt'},
'tam':{'label':'Tamil', 'for_espeak':'ta'},
'pol':{'label':'Polish', 'for_espeak':'pl'},
'rus':{'label':'Russian', 'for_espeak':'ru'},
'isl':{'label':'Icelandic', 'for_espeak':'is'},
'rom':{'label':'Romanian', 'for_espeak':'ro'},
'ces':{'label':'Czech', 'for_espeak':'cs'},
'slk':{'label':'Slovak', 'for_espeak':'sk'},
'bul':{'label':'Bulgarian', 'for_espeak':'bg'},
'cat':{'label':'Catalan', 'for_espeak':'ca'},
'ben':{'label':'Bangla', 'for_espeak':''}, 
'eng':{'label':'English', 'for_espeak':'en-uk-rp'}, 
'urd':{'label':'Urdu', 'for_espeak':''},
'amh':{'label':'Amharic', 'for_espeak':''},
'slv':{'label':'Slovenian', 'for_espeak':''},
'vie':{'label':'Vietnamese', 'for_espeak':'vi'},
'tur':{'label':'Turkish', 'for_espeak':'tr'},
'hye':{'label':'Armenian', 'for_espeak':'hy'},
'prs':{'label':'Dari', 'for_espeak':'fa'},
'fil':{'label':'Filipino', 'for_espeak':''},
'far':{'label':'Farsi', 'for_espeak':'fa'},
'pes':{'label':'Persian', 'for_espeak':'fa'},
'pus':{'label':'Pashto', 'for_espeak':''},
'mkd':{'label':'Macedonian', 'for_espeak':'mk'},
'lit':{'label':'Lithuanian', 'for_espeak':'lt'},
'ckb':{'label':'Sorani', 'for_espeak':''},
'kmr':{'label':'Kurmanji', 'for_espeak':'ku'},
'sqi':{'label':'Albanian', 'for_espeak':'sq'},
'som':{'label':'Somalian', 'for_espeak':''},
'ara':{'label':'Standard Arabic', 'for_espeak':''},
'apc':{'label':'Syrian Arabic', 'for_espeak':''},
'nid':{'label':'Dutch', 'for_espeak':'nl'},#until gd is updated
'nld':{'label':'Dutch', 'for_espeak':'nl'}
=======
iso6393dic ={
 'hbs':{'label':'Serbo-Croatian'},
'deu':{'label':'German'},
'swe':{'label':'Swedish'},
'nor':{'label':'Norwegian'}, 
'fin':{'label':'Finnish'},
'dan':{'label':'Danish'},
'tir':{'label':'Tigrinya'},
'spa':{'label':'Spanish'},
'ita':{'label':'Italian'},
'fra':{'label':'French'},
'ell':{'label':'Greek'},
'hun':{'label':'Hungarian'},
'por':{'label':'Portuguese'},
'tam':{'label':'Tamil'},
'pol':{'label':'Polish'},
'rus':{'label':'Russian'},
'isl':{'label':'Icelandic'},  
'rom':{'label':'Romanian'},
'ces':{'label':'Czech'},
'slk':{'label':'Slovak'},
'bul':{'label':'Bulgarian'},
'cat':{'label':'Catalan'},
'ben':{'label':'Bangla'}, 
'urd':{'label':'Urdu'},
'amh':{'label':'Amharic'},
'slv':{'label':'Slovenian'},
'vie':{'label':'Vietnamese'},
'tur':{'label':'Turkish'},
'hye':{'label':'Armenian'}, 
'prs':{'label':'Dari'},
'fil':{'label':'Filipino'},
'far':{'label':'Farsi'},
'pus':{'label':'Pashto'},
'pes':{'label':'Persian'},
'mkd':{'label':'Macedonian'},
'lit':{'label':'Lithuanian'},
'ckb':{'label':'Sorani'},
'kmr':{'label':'Kurmanji'},
'sqi':{'label':'Albanian'},
'som':{'label':'Somalian'},
'ara':{'label':'Standard Arabic'},
'apc':{'label':'Syrian Arabic'},
'nid':{'label':'Dutch'},#until gd is updated
'nld':{'label':'Dutch'}


>>>>>>> Stashed changes
}